import { useState } from "react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Activity, ArrowDownRight, ArrowUpRight, Check, CircleDollarSign, Clock3, MoreHorizontal, Plus, Search, TicketCheck, Users } from "lucide-react";
import toast from "react-hot-toast";
import { Button } from "../components/ui";

const revenue = [{m:"Jan",v:32},{m:"Feb",v:38},{m:"Mar",v:43},{m:"Apr",v:51},{m:"May",v:58},{m:"Jun",v:67},{m:"Jul",v:74},{m:"Aug",v:81},{m:"Sep",v:89},{m:"Oct",v:97},{m:"Nov",v:108},{m:"Dec",v:121}];
const users = [
  {name:"Maya Chen",email:"maya@northstar.co",plan:"Growth",status:"Active",joined:"Jun 8, 2026"},
  {name:"Ethan Brooks",email:"ethan@alder.co",plan:"Enterprise",status:"Active",joined:"Jun 7, 2026"},
  {name:"Priya Shah",email:"priya@layerpath.io",plan:"Starter",status:"Trial",joined:"Jun 5, 2026"},
  {name:"Leo Martin",email:"leo@modulo.dev",plan:"Growth",status:"Past due",joined:"Jun 3, 2026"},
  {name:"Sara Kim",email:"sara@brightway.co",plan:"Growth",status:"Active",joined:"May 30, 2026"},
];
const tickets = [{id:"NX-1048",subject:"DNS records for launch",user:"Maya Chen",priority:"High",status:"In Progress",assignee:"Amelia"}, {id:"NX-1046",subject:"Facebook pixel issue",user:"Leo Martin",priority:"Critical",status:"Open",assignee:"Unassigned"}, {id:"NX-1042",subject:"New user onboarding",user:"Sara Kim",priority:"Low",status:"Resolved",assignee:"Noah"}];
const kpis = [[Users,"1,284","Total users","+12.4%"],[Activity,"924","Active subscriptions","+8.2%"],[CircleDollarSign,"$121k","Monthly recurring revenue","+14.7%"],[TicketCheck,"38","Open tickets","-6.1%"]];

function ChartTooltip({ active, payload, label }) {
  if (!active || !payload?.length) return null;
  return <div className="rounded-xl border border-slate-200 bg-white p-3 text-xs shadow-xl dark:border-white/10 dark:bg-ink"><div className="font-bold">{label}</div><div className="mt-1 text-electric">${payload[0].value}k</div></div>;
}

export function AdminOverview() {
  return <div className="space-y-7"><div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-4">{kpis.map(([Icon,value,label,change],i)=><div className="panel p-5" key={label}><div className="flex items-start justify-between"><span className="grid size-11 place-items-center rounded-xl bg-blue-50 text-electric dark:bg-blue-500/10"><Icon size={20}/></span><span className={`flex items-center text-xs font-bold ${i===3?"text-emerald-600":"text-emerald-600"}`}>{i===3?<ArrowDownRight size={14}/>:<ArrowUpRight size={14}/>} {change}</span></div><div className="mt-5 text-2xl font-extrabold">{value}</div><div className="mt-1 text-sm text-slate-500">{label}</div></div>)}</div><div className="grid gap-7 xl:grid-cols-[1.5fr_.7fr]"><div className="panel p-6"><div><h2 className="font-bold">Revenue overview</h2><p className="mt-1 text-xs text-slate-500">Monthly recurring revenue, 2026</p></div><div className="mt-7 h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={revenue}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#94a3b822"/><XAxis dataKey="m" axisLine={false} tickLine={false} fontSize={11}/><YAxis axisLine={false} tickLine={false} fontSize={11}/><Tooltip content={<ChartTooltip/>}/><Bar dataKey="v" fill="#3B82F6" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></div></div><div className="panel p-6"><h2 className="font-bold">Ticket status</h2><p className="mt-1 text-xs text-slate-500">Current support workload</p><div className="h-56"><ResponsiveContainer><PieChart><Pie data={[{n:"Open",v:38},{n:"Progress",v:24},{n:"Resolved",v:67}]} dataKey="v" nameKey="n" innerRadius={52} outerRadius={76} paddingAngle={4}>{["#3B82F6","#F59E0B","#10B981"].map(c=><Cell key={c} fill={c}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></div><div className="flex justify-center gap-5">{[["Open","bg-blue-500"],["Progress","bg-amber-500"],["Resolved","bg-emerald-500"]].map(([l,c])=><span className="flex items-center gap-2 text-xs text-slate-500" key={l}><i className={`size-2 rounded-full ${c}`}/>{l}</span>)}</div></div></div><AdminTable title="Recent signups" rows={users.slice(0,4)}/></div>;
}

function AdminTable({ title="Users", rows=users }) {
  return <div className="panel overflow-hidden"><div className="flex items-center justify-between p-6"><h2 className="font-bold">{title}</h2><button className="text-sm font-bold text-electric">View all</button></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wider text-slate-500 dark:bg-white/5"><tr><th className="p-5">User</th><th>Plan</th><th>Status</th><th>Joined</th><th></th></tr></thead><tbody>{rows.map(user=><tr className="border-t border-slate-100 dark:border-white/10" key={user.email}><td className="p-5"><div className="font-semibold">{user.name}</div><div className="mt-1 text-xs text-slate-400">{user.email}</div></td><td>{user.plan}</td><td><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${user.status==="Active"?"bg-emerald-50 text-emerald-600 dark:bg-emerald-500/10":"bg-amber-50 text-amber-600 dark:bg-amber-500/10"}`}>{user.status}</span></td><td className="text-slate-500">{user.joined}</td><td><button><MoreHorizontal size={18}/></button></td></tr>)}</tbody></table></div></div>;
}

export function AdminUsers() {
  const [query,setQuery]=useState(""); const filtered=users.filter(u=>(u.name+u.email).toLowerCase().includes(query.toLowerCase()));
  return <div><div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h2 className="text-2xl font-bold">User management</h2><p className="mt-1 text-sm text-slate-500">Manage accounts, access and assigned plans.</p></div><Button><Plus size={16}/>Add user</Button></div><div className="panel mb-5 flex flex-col gap-3 p-4 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-3.5 text-slate-400" size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} className="input pl-10" placeholder="Search users..."/></div><select className="input sm:w-44"><option>All plans</option><option>Starter</option><option>Growth</option><option>Enterprise</option></select><select className="input sm:w-44"><option>All statuses</option><option>Active</option><option>Trial</option><option>Past due</option></select></div><AdminTable rows={filtered}/></div>;
}

export function AdminSubscriptions() {
  return <div><div className="mb-7"><h2 className="text-2xl font-bold">Subscriptions</h2><p className="mt-1 text-sm text-slate-500">Monitor plan health, billing cycles and payment status.</p></div><div className="grid gap-5 sm:grid-cols-3">{[["924","Active"],["18","Past due"],["32","Churned this month"]].map(([v,l])=><div className="panel p-5" key={l}><div className="text-2xl font-extrabold">{v}</div><div className="mt-1 text-sm text-slate-500">{l}</div></div>)}</div><div className="panel mt-6 overflow-hidden"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500 dark:bg-white/5"><tr><th className="p-5">Customer</th><th>Plan</th><th>Cycle</th><th>Status</th><th>Next billing</th><th></th></tr></thead><tbody>{users.map((u,i)=><tr className="border-t border-slate-100 dark:border-white/10" key={u.email}><td className="p-5 font-semibold">{u.name}</td><td>{u.plan}</td><td>{i%2?"Annual":"Monthly"}</td><td className="text-emerald-600">{u.status}</td><td>Jul {i+1}, 2026</td><td><MoreHorizontal size={18}/></td></tr>)}</tbody></table></div></div>;
}

export function AdminTickets() {
  return <div><div className="mb-7"><h2 className="text-2xl font-bold">Support queue</h2><p className="mt-1 text-sm text-slate-500">Triage, assign and resolve customer requests.</p></div><div className="grid gap-4">{tickets.map(t=><div className="panel flex flex-col justify-between gap-5 p-5 sm:flex-row sm:items-center" key={t.id}><div className="flex items-start gap-4"><span className={`mt-1 size-2 rounded-full ${t.priority==="Critical"?"bg-red-500":t.priority==="High"?"bg-orange-500":"bg-blue-500"}`}/><div><div className="font-semibold">{t.subject}</div><div className="mt-1 text-xs text-slate-500">{t.id} · {t.user} · {t.priority} priority</div></div></div><div className="flex items-center gap-5"><span className="text-xs font-semibold text-slate-500">{t.assignee}</span><select className="rounded-lg border border-slate-200 bg-transparent px-3 py-2 text-xs font-bold dark:border-white/10"><option>{t.status}</option><option>Open</option><option>In Progress</option><option>Resolved</option></select></div></div>)}</div></div>;
}

export function AdminAnalytics() {
  const trends=revenue.map((r,i)=>({...r,new:34+i*3,churn:8+(i%3)*2}));
  return <div><div className="mb-7"><h2 className="text-2xl font-bold">Analytics & revenue</h2><p className="mt-1 text-sm text-slate-500">Growth, retention and service mix at a glance.</p></div><div className="grid gap-6 xl:grid-cols-2"><div className="panel p-6"><h3 className="font-bold">MRR growth</h3><div className="mt-6 h-72"><ResponsiveContainer><AreaChart data={revenue}><defs><linearGradient id="mrr" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#3B82F6" stopOpacity=".35"/><stop offset="1" stopColor="#3B82F6" stopOpacity="0"/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#94a3b822"/><XAxis dataKey="m" axisLine={false} tickLine={false} fontSize={11}/><YAxis axisLine={false} tickLine={false} fontSize={11}/><Tooltip/><Area type="monotone" dataKey="v" stroke="#3B82F6" fill="url(#mrr)" strokeWidth={3}/></AreaChart></ResponsiveContainer></div></div><div className="panel p-6"><h3 className="font-bold">Subscriber movement</h3><div className="mt-6 h-72"><ResponsiveContainer><LineChart data={trends}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#94a3b822"/><XAxis dataKey="m" axisLine={false} tickLine={false} fontSize={11}/><YAxis axisLine={false} tickLine={false} fontSize={11}/><Tooltip/><Legend/><Line dataKey="new" stroke="#10B981" strokeWidth={3} dot={false}/><Line dataKey="churn" stroke="#F43F5E" strokeWidth={3} dot={false}/></LineChart></ResponsiveContainer></div></div></div><div className="mt-6 grid gap-6 lg:grid-cols-2"><div className="panel p-6"><h3 className="font-bold">Service popularity</h3><div className="mt-6 space-y-5">{[["SEO",82],["Web services",71],["IT support",59],["Digital ads",47]].map(([l,v])=><div key={l}><div className="flex justify-between text-sm"><span>{l}</span><b>{v}%</b></div><div className="mt-2 h-2 rounded-full bg-slate-100 dark:bg-white/10"><div className={`h-full rounded-full bg-electric ${v>80?"w-10/12":v>70?"w-8/12":v>50?"w-7/12":"w-1/2"}`}/></div></div>)}</div></div><div className="panel p-6"><h3 className="font-bold">Top plan</h3><div className="mt-8 text-4xl font-extrabold">Growth</div><p className="mt-2 text-sm text-slate-500">62% of active subscriptions · $71.4k MRR</p><div className="mt-8 flex items-center gap-2 text-sm font-bold text-emerald-600"><ArrowUpRight size={17}/> 9.8% month over month</div></div></div></div>;
}

export function AdminGeneric({ type }) {
  const isSettings=type==="Settings";
  const save=e=>{e.preventDefault();toast.success(`${type} saved.`)};
  return <div><div className="mb-7"><h2 className="text-2xl font-bold">{type}</h2><p className="mt-1 text-sm text-slate-500">{isSettings?"Configure plans, roles and operational preferences.":`Manage Nextexa ${type.toLowerCase()} content and records.`}</p></div>{isSettings?<form onSubmit={save} className="panel max-w-3xl p-7"><h3 className="font-bold">Workspace settings</h3><div className="mt-6 grid gap-5 sm:grid-cols-2"><label className="text-sm font-semibold">Company name<input className="input mt-2" defaultValue="Nextexa Lab"/></label><label className="text-sm font-semibold">Support email<input className="input mt-2" defaultValue="support@nextexa.lab"/></label><label className="text-sm font-semibold">Default currency<select className="input mt-2"><option>USD</option><option>EUR</option><option>GBP</option></select></label><label className="text-sm font-semibold">Default user role<select className="input mt-2"><option>Support Agent</option><option>Billing Manager</option><option>Super Admin</option></select></label></div><Button className="mt-7">Save settings</Button></form>:<div className="panel p-10 text-center"><span className="mx-auto grid size-14 place-items-center rounded-2xl bg-blue-50 text-electric dark:bg-blue-500/10"><Clock3/></span><h3 className="mt-5 text-lg font-bold">{type} manager</h3><p className="mx-auto mt-2 max-w-md text-sm text-slate-500">Create, publish and manage {type.toLowerCase()} from this workspace. API endpoints are ready for live data.</p><Button className="mt-6"><Plus size={16}/>Create new</Button></div>}</div>;
}
