import { useState } from "react";
import { ArrowRight, CalendarDays, CheckCircle2, Clock3, CreditCard, Download, Globe2, Headphones, Plus, Search, Settings2, TrendingUp } from "lucide-react";
import toast from "react-hot-toast";
import { Button } from "../components/ui";
import { useTickets } from "../hooks/useTickets";

const serviceItems = [
  { title: "Organic growth", type: "SEO", status: "Active", progress: 68, width: "w-2/3", icon: Search },
  { title: "Website care", type: "Web", status: "Active", progress: 42, width: "w-5/12", icon: Globe2 },
  { title: "Team help desk", type: "IT Support", status: "Active", progress: 81, width: "w-10/12", icon: Headphones },
];
const invoices = [{ id: "INV-2048", date: "Jun 1, 2026", amount: "$999.00", status: "Paid" }, { id: "INV-1992", date: "May 1, 2026", amount: "$999.00", status: "Paid" }, { id: "INV-1928", date: "Apr 1, 2026", amount: "$999.00", status: "Paid" }];

export function Overview() {
  return <div className="space-y-7"><div className="overflow-hidden rounded-3xl bg-gradient-to-r from-blue-600 to-blue-800 p-7 text-white"><div className="flex flex-col justify-between gap-7 sm:flex-row sm:items-end"><div><div className="text-sm text-blue-200">Current plan</div><h2 className="mt-2 text-3xl font-extrabold">Growth</h2><p className="mt-2 text-sm text-blue-100">3 active services · Unlimited requests</p></div><Button to="/pricing" variant="secondary" className="border-white/20 bg-white/10 text-white">Manage plan <ArrowRight size={16}/></Button></div></div><div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-4">{[[TrendingUp,"12","Requests completed","+18% this month"],[Clock3,"3","In progress","Across 3 services"],[CalendarDays,"Jul 1","Next billing date","$999.00 scheduled"],[CheckCircle2,"94%","Satisfaction score","From 16 ratings"]].map(([Icon,value,label,copy]) => <div className="panel p-5" key={label}><Icon size={20} className="text-electric"/><div className="mt-5 text-2xl font-extrabold">{value}</div><div className="mt-1 text-sm font-semibold">{label}</div><div className="mt-1 text-xs text-slate-500">{copy}</div></div>)}</div><div className="grid gap-7 xl:grid-cols-[1.3fr_.7fr]"><div className="panel p-6"><div className="flex items-center justify-between"><h3 className="font-bold">Active work</h3><Button to="/dashboard/services" variant="ghost">View all</Button></div><div className="mt-4 space-y-4">{serviceItems.map(({ title, type, progress, width }) => <div className="rounded-2xl border border-slate-100 p-4 dark:border-white/10" key={title}><div className="flex justify-between"><div><div className="font-semibold">{title}</div><div className="mt-1 text-xs text-slate-500">{type}</div></div><span className="h-fit rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-bold text-emerald-600 dark:bg-emerald-500/10">ON TRACK</span></div><div className="mt-4 h-1.5 rounded-full bg-slate-100 dark:bg-white/10"><div className={`h-full rounded-full bg-electric ${width}`} /></div><span className="sr-only">{progress}% complete</span></div>)}</div></div><div className="panel p-6"><h3 className="font-bold">Your strategist</h3><div className="mt-6 flex items-center gap-4"><span className="grid size-14 place-items-center rounded-full bg-gradient-to-br from-violet-400 to-blue-500 text-lg font-bold text-white">AM</span><div><div className="font-bold">Amelia Morgan</div><div className="text-xs text-slate-500">Growth strategist</div></div></div><p className="mt-6 text-sm leading-6 text-slate-500">Your next strategy call is Thursday, June 18 at 10:00 AM.</p><Button to="/contact" variant="secondary" className="mt-6 w-full">Message Amelia</Button></div></div></div>;
}

export function MyServices() {
  return <div><div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h2 className="text-2xl font-bold">Your service workspace</h2><p className="mt-1 text-sm text-slate-500">Track progress and manage priorities across your subscription.</p></div><Button><Plus size={16}/>New request</Button></div><div className="grid gap-6 lg:grid-cols-3">{serviceItems.map(({ title,type,status,progress,width,icon:Icon }) => <div className="panel p-6" key={title}><div className="flex items-start justify-between"><span className="grid size-12 place-items-center rounded-2xl bg-blue-50 text-electric dark:bg-blue-500/10"><Icon/></span><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-bold text-emerald-600 dark:bg-emerald-500/10">{status}</span></div><div className="mt-6 text-xs font-bold uppercase tracking-wider text-electric">{type}</div><h3 className="mt-2 text-xl font-bold">{title}</h3><div className="mt-6 flex justify-between text-xs"><span className="text-slate-500">Monthly roadmap</span><span className="font-bold">{progress}%</span></div><div className="mt-2 h-2 rounded-full bg-slate-100 dark:bg-white/10"><div className={`h-full rounded-full bg-electric ${width}`} /></div><Button variant="secondary" className="mt-6 w-full">Open workspace</Button></div>)}</div></div>;
}

export function Tickets() {
  const { tickets, createTicket } = useTickets(); const [open, setOpen] = useState(false);
  const submit = e => { e.preventDefault(); const data = new FormData(e.currentTarget); createTicket({subject:data.get("subject"),priority:data.get("priority")}); setOpen(false); toast.success("Ticket created."); };
  return <div><div className="mb-7 flex items-center justify-between"><div><h2 className="text-2xl font-bold">Support tickets</h2><p className="mt-1 text-sm text-slate-500">Ask for help and follow every conversation.</p></div><Button onClick={() => setOpen(true)}><Plus size={16}/>New ticket</Button></div>{open && <form onSubmit={submit} className="panel mb-6 grid gap-4 p-6 sm:grid-cols-[1fr_180px_auto]"><input name="subject" required className="input" placeholder="What do you need help with?"/><select name="priority" className="input"><option>Low</option><option>Medium</option><option>High</option><option>Critical</option></select><Button>Create ticket</Button></form>}<div className="panel overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wider text-slate-500 dark:bg-white/5"><tr><th className="p-5">Ticket</th><th>Priority</th><th>Status</th><th>Updated</th><th></th></tr></thead><tbody>{tickets.map(ticket => <tr className="border-t border-slate-100 dark:border-white/10" key={ticket.id}><td className="p-5"><div className="font-semibold">{ticket.subject}</div><div className="mt-1 text-xs text-slate-400">{ticket.id}</div></td><td><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold dark:bg-white/10">{ticket.priority}</span></td><td><span className="text-xs font-bold text-blue-600">{ticket.status}</span></td><td className="text-slate-500">{ticket.updated}</td><td><button className="font-bold text-electric">View</button></td></tr>)}</tbody></table></div></div></div>;
}

export function Invoices() {
  return <div><h2 className="text-2xl font-bold">Billing history</h2><p className="mt-1 text-sm text-slate-500">View and download your Nextexa invoices.</p><div className="panel mt-7 overflow-hidden"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500 dark:bg-white/5"><tr><th className="p-5">Invoice</th><th>Date</th><th>Amount</th><th>Status</th><th></th></tr></thead><tbody>{invoices.map(invoice => <tr className="border-t border-slate-100 dark:border-white/10" key={invoice.id}><td className="p-5 font-semibold">{invoice.id}</td><td>{invoice.date}</td><td>{invoice.amount}</td><td><span className="text-xs font-bold text-emerald-600">{invoice.status}</span></td><td><button onClick={() => toast.success("Invoice download started.")}><Download size={17}/></button></td></tr>)}</tbody></table></div></div>;
}

export function AccountSettings() {
  const save = e => { e.preventDefault(); toast.success("Settings saved."); };
  return <div className="mx-auto max-w-3xl"><form onSubmit={save} className="panel p-7"><div className="flex items-center gap-4 border-b border-slate-100 pb-6 dark:border-white/10"><span className="grid size-16 place-items-center rounded-full bg-gradient-to-br from-blue-500 to-cyan-400 text-xl font-bold text-white">JL</span><div><h2 className="font-bold">Profile details</h2><p className="text-sm text-slate-500">Keep your contact information current.</p></div></div><div className="mt-6 grid gap-5 sm:grid-cols-2"><label className="text-sm font-semibold">Full name<input className="input mt-2" defaultValue="Jordan Lee"/></label><label className="text-sm font-semibold">Email<input className="input mt-2" defaultValue="user@nextexa.dev"/></label><label className="text-sm font-semibold">Company<input className="input mt-2" defaultValue="Northstar Labs"/></label><label className="text-sm font-semibold">Timezone<select className="input mt-2"><option>Eastern Time (US)</option><option>Pacific Time (US)</option><option>UTC</option></select></label></div><div className="mt-8 flex justify-end"><Button>Save changes</Button></div></form><div className="panel mt-6 p-7"><div className="flex gap-3"><CreditCard className="text-electric"/><div><h3 className="font-bold">Payment method</h3><p className="mt-1 text-sm text-slate-500">Visa ending in 4242 · Expires 08/28</p></div></div><Button variant="secondary" className="mt-5"><Settings2 size={16}/>Update billing</Button></div></div>;
}
